from __future__ import annotations
from enum import StrEnum
class JobState(StrEnum):
    CREATED="CREATED"; ENVIRONMENT_SCANNED="ENVIRONMENT_SCANNED"; FILES_DISCOVERED="FILES_DISCOVERED"; RULES_COMPILED="RULES_COMPILED"; PLAN_VALIDATED="PLAN_VALIDATED"; PREVIEWED="PREVIEWED"
    PREPARED="PREPARED"; RUNNING="RUNNING"; SAVING_TEMP="SAVING_TEMP"; CANDIDATE_SAVED="CANDIDATE_SAVED"; VERIFYING="VERIFYING"; COMMITTED="COMMITTED"
    PAUSED="PAUSED"; CANCELLING="CANCELLING"; FAILED="FAILED"; REJECTED="REJECTED"; ROLLED_BACK="ROLLED_BACK"; CLEANED="CLEANED"; RECOVERY_REQUIRED="RECOVERY_REQUIRED"
    SUCCESS="SUCCESS"; SUCCESS_WITH_WARNINGS="SUCCESS_WITH_WARNINGS"; PARTIAL_SUCCESS="PARTIAL_SUCCESS"; CANCELLED="CANCELLED"
_ALLOWED = {
    JobState.CREATED:{JobState.ENVIRONMENT_SCANNED,JobState.PREPARED,JobState.FAILED},
    JobState.ENVIRONMENT_SCANNED:{JobState.FILES_DISCOVERED,JobState.FAILED},
    JobState.FILES_DISCOVERED:{JobState.RULES_COMPILED,JobState.FAILED},
    JobState.RULES_COMPILED:{JobState.PLAN_VALIDATED,JobState.FAILED},
    JobState.PLAN_VALIDATED:{JobState.PREVIEWED,JobState.FAILED},
    JobState.PREVIEWED:{JobState.PREPARED,JobState.RUNNING,JobState.FAILED},
    JobState.PREPARED:{JobState.RUNNING,JobState.FAILED,JobState.REJECTED},
    JobState.RUNNING:{JobState.PAUSED,JobState.CANCELLING,JobState.FAILED,JobState.SAVING_TEMP,JobState.CANDIDATE_SAVED,JobState.REJECTED},
    JobState.PAUSED:{JobState.RUNNING,JobState.CANCELLING,JobState.FAILED},
    JobState.CANCELLING:{JobState.ROLLED_BACK}, JobState.FAILED:{JobState.REJECTED,JobState.ROLLED_BACK},
    JobState.SAVING_TEMP:{JobState.CANDIDATE_SAVED,JobState.VERIFYING,JobState.FAILED},
    JobState.CANDIDATE_SAVED:{JobState.VERIFYING,JobState.FAILED,JobState.REJECTED},
    JobState.VERIFYING:{JobState.COMMITTED,JobState.REJECTED,JobState.FAILED},
    JobState.REJECTED:{JobState.ROLLED_BACK}, JobState.ROLLED_BACK:{JobState.CLEANED},
    JobState.COMMITTED:{JobState.CLEANED,JobState.SUCCESS,JobState.SUCCESS_WITH_WARNINGS,JobState.PARTIAL_SUCCESS}, JobState.CLEANED:set(), JobState.RECOVERY_REQUIRED:set(),
    JobState.SUCCESS:{JobState.CLEANED}, JobState.SUCCESS_WITH_WARNINGS:{JobState.CLEANED}, JobState.PARTIAL_SUCCESS:{JobState.CLEANED}, JobState.CANCELLED:{JobState.ROLLED_BACK},
}
def assert_transition(current: JobState, next_state: JobState) -> None:
    if current == next_state: return
    if next_state not in _ALLOWED.get(current, set()): raise ValueError(f"Invalid job state transition: {current} -> {next_state}")
